In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
import warnings
import datetime
warnings.filterwarnings('ignore')
%matplotlib inline

In [29]:
weather = pd.read_csv("hourly_weather_delhi.csv", skiprows=3)

print(weather.head())

               time  temperature_2m (°C)  relative_humidity_2m (%)  rain (mm)  \
0  2015-01-01T00:00                 11.8                        87        0.0
1  2015-01-01T01:00                 12.5                        82        0.0
2  2015-01-01T02:00                 12.9                        80        0.0
3  2015-01-01T03:00                 12.9                        79        0.0
4  2015-01-01T04:00                 12.8                        79        0.0

   wind_speed_10m (m/s)  wind_direction_10m (°)
0                  2.12                      19
1                  2.62                      18
2                  2.47                      14
3                  2.06                      14
4                  1.71                       7

In [18]:
weather.rename(columns={
    "time": "Datetime",
    "temperature_2m (°C)": "Temperature",
    "wind_speed_10m (m/s)": "WindSpeed",
    "wind_direction_10m (°)": "WindDirection",
    "rain (mm)": "Rain",
    "relative_humidity_2m (%)": "Humidity"
}, inplace=True)

In [19]:
print(weather.columns.tolist())

['Datetime', 'Temperature', 'Humidity', 'Rain', 'WindSpeed', 'WindDirection']

In [20]:
weather.head()

           Datetime  Temperature  Humidity  Rain  WindSpeed  WindDirection
0  2015-01-01T00:00         11.8        87   0.0       2.12             19
1  2015-01-01T01:00         12.5        82   0.0       2.62             18
2  2015-01-01T02:00         12.9        80   0.0       2.47             14
3  2015-01-01T03:00         12.9        79   0.0       2.06             14
4  2015-01-01T04:00         12.8        79   0.0       1.71              7

In [23]:
weather["Datetime"] = pd.to_datetime(weather["Datetime"])

In [22]:
print(weather.head())

             Datetime  Temperature  Humidity  Rain  WindSpeed  WindDirection
0 2015-01-01 00:00:00         11.8        87   0.0       2.12             19
1 2015-01-01 01:00:00         12.5        82   0.0       2.62             18
2 2015-01-01 02:00:00         12.9        80   0.0       2.47             14
3 2015-01-01 03:00:00         12.9        79   0.0       2.06             14
4 2015-01-01 04:00:00         12.8        79   0.0       1.71              7

In [24]:
weather["Date"] = weather["Datetime"].dt.date

In [25]:
weather.head()

,Datetime,Temperature,Humidity,Rain,WindSpeed,WindDirection,Date
0,2015-01-01 00:00:00,11.8,87,0.0,2.12,19,2015-01-01
1,2015-01-01 01:00:00,12.5,82,0.0,2.62,18,2015-01-01
2,2015-01-01 02:00:00,12.9,80,0.0,2.47,14,2015-01-01
3,2015-01-01 03:00:00,12.9,79,0.0,2.06,14,2015-01-01
4,2015-01-01 04:00:00,12.8,79,0.0,1.71,7,2015-01-01

In [26]:
daily_weather = weather.groupby("Date").agg({
    "Temperature": "mean",
    "Humidity": "mean",
    "WindSpeed": "mean",
    "WindDirection": "mean",
    "Rain": "sum"
}).reset_index()

In [27]:
daily_weather.head()

         Date  Temperature   Humidity  WindSpeed  WindDirection  Rain
0  2015-01-01    16.145833  68.083333   1.660000      95.708333   0.0
1  2015-01-02    15.037500  84.166667   1.600417      88.916667   3.4
2  2015-01-03    15.441667  84.000000   1.421667     276.791667   0.5
3  2015-01-04    14.162500  79.250000   2.807500     313.291667   0.0
4  2015-01-05    13.995833  74.208333   5.365417     299.041667   0.0

In [28]:
print("Hourly rows:", len(weather))
print("Daily rows:", len(daily_weather))

Hourly rows: 87192
Daily rows: 3633

## Filter AQI data of delhi from AQI.csv dataset

In [30]:
daily_AQI_delhi = pd.read_csv("AQI.csv")

print(daily_AQI_delhi.head())

        City    Datetime   PM25   PM10     NO   NO2    NOx   NH3    CO   SO2  \
0      Delhi  2015-01-01  153.3  241.7  182.9  33.0   81.3  38.5  1.87  64.5
1     Mumbai  2015-01-01   70.5  312.7  195.0  42.0  122.5  31.5  7.22  83.8
2    Chennai  2015-01-01  174.1  275.4   56.2  68.8  230.9  28.5  8.56  60.8
3    Kolkata  2015-01-01  477.2  543.9   14.1  76.4  225.9  45.6  2.41  42.1
4  Bangalore  2015-01-01  171.6  117.7  123.3  12.4   61.9  49.7  1.26  79.7

      O3  Benzene  Toluene  Xylene    AQI    AQI_Bucket
0   83.6    18.93    20.81    8.32  204.5        Severe
1  108.0     2.01    19.41    2.86   60.9  Satisfactory
2   43.9    19.07    10.19    9.63  486.5        Severe
3  171.1     9.31    11.65    9.39  174.4     Very Poor
4  164.3     6.04    12.74    9.59  489.7          Good

In [31]:
aqi_delhi = daily_AQI_delhi[daily_AQI_delhi["City"] == "Delhi"].copy()

In [32]:
print(aqi_delhi.head())
print(aqi_delhi.shape)

     City    Datetime   PM25   PM10     NO    NO2    NOx   NH3    CO   SO2  \
0   Delhi  2015-01-01  153.3  241.7  182.9   33.0   81.3  38.5  1.87  64.5
5   Delhi  2015-01-02  344.2  173.2  179.8  128.4  156.1  15.6  6.28   7.5
10  Delhi  2015-01-03  473.9   20.1   12.7  102.7  244.7  42.5  0.04  29.8
15  Delhi  2015-01-04   32.4  414.8  198.1   25.6  218.2  13.2  2.47  50.4
20  Delhi  2015-01-05  312.8  155.8  143.1  106.8    6.1   4.9  4.04   2.0

       O3  Benzene  Toluene  Xylene    AQI    AQI_Bucket
0    83.6    18.93    20.81    8.32  204.5        Severe
5     9.4     0.55    15.60    2.45  238.5  Satisfactory
10   42.0     1.87    15.11    2.41   77.6  Satisfactory
15   80.2     7.70    12.46    0.57   85.4  Satisfactory
20  101.3    13.41     1.66    4.46  396.8          Poor
(3653, 16)

In [34]:
aqi_delhi.rename(columns={
    "Datetime": "Date"
}, inplace=True)

In [38]:
aqi_delhi.head()

,City,Date,PM25,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Delhi,2015-01-01,153.3,241.7,182.9,33.0,81.3,38.5,1.87,64.5,83.6,18.93,20.81,8.32,204.5,Severe
5,Delhi,2015-01-02,344.2,173.2,179.8,128.4,156.1,15.6,6.28,7.5,9.4,0.55,15.60,2.45,238.5,Satisfactory
10,Delhi,2015-01-03,473.9,20.1,12.7,102.7,244.7,42.5,0.04,29.8,42.0,1.87,15.11,2.41,77.6,Satisfactory
15,Delhi,2015-01-04,32.4,414.8,198.1,25.6,218.2,13.2,2.47,50.4,80.2,7.70,12.46,0.57,85.4,Satisfactory
20,Delhi,2015-01-05,312.8,155.8,143.1,106.8,6.1,4.9,4.04,2.0,101.3,13.41,1.66,4.46,396.8,Poor

In [39]:
print(aqi_delhi["Date"].dtype)
print(daily_weather["Date"].dtype)

object
object

In [40]:
aqi_delhi["Date"] = pd.to_datetime(aqi_delhi["Date"])
daily_weather["Date"] = pd.to_datetime(daily_weather["Date"])

In [41]:
print(aqi_delhi["Date"].dtype)
print(daily_weather["Date"].dtype)

datetime64[ns]
datetime64[ns]

In [42]:
print(aqi_delhi["Date"].head())
print(daily_weather["Date"].head())

0    2015-01-01
5    2015-01-02
10   2015-01-03
15   2015-01-04
20   2015-01-05
Name: Date, dtype: datetime64[ns]
0   2015-01-01
1   2015-01-02
2   2015-01-03
3   2015-01-04
4   2015-01-05
Name: Date, dtype: datetime64[ns]

In [43]:
merged = pd.merge(
    aqi_delhi,
    daily_weather,
    left_on="Date",
    right_on="Date",
    how="inner"
)

In [44]:
print(merged.head())

    City       Date   PM25   PM10     NO    NO2    NOx   NH3    CO   SO2  ...  \
0  Delhi 2015-01-01  153.3  241.7  182.9   33.0   81.3  38.5  1.87  64.5  ...
1  Delhi 2015-01-02  344.2  173.2  179.8  128.4  156.1  15.6  6.28   7.5  ...
2  Delhi 2015-01-03  473.9   20.1   12.7  102.7  244.7  42.5  0.04  29.8  ...
3  Delhi 2015-01-04   32.4  414.8  198.1   25.6  218.2  13.2  2.47  50.4  ...
4  Delhi 2015-01-05  312.8  155.8  143.1  106.8    6.1   4.9  4.04   2.0  ...

   Benzene  Toluene  Xylene    AQI    AQI_Bucket Temperature   Humidity  \
0    18.93    20.81    8.32  204.5        Severe   16.145833  68.083333
1     0.55    15.60    2.45  238.5  Satisfactory   15.037500  84.166667
2     1.87    15.11    2.41   77.6  Satisfactory   15.441667  84.000000
3     7.70    12.46    0.57   85.4  Satisfactory   14.162500  79.250000
4    13.41     1.66    4.46  396.8          Poor   13.995833  74.208333

   WindSpeed  WindDirection  Rain
0   1.660000      95.708333   0.0
1   1.600417      88.916667   3.4
2   1.421667     276.791667   0.5
3   2.807500     313.291667   0.0
4   5.365417     299.041667   0.0

[5 rows x 21 columns]

In [45]:
merged["month"] = merged["Date"].dt.month
merged["day_of_week"] = merged["Date"].dt.dayofweek
merged["day_of_year"] = merged["Date"].dt.dayofyear

In [46]:
merged.head()

,City,Date,PM25,PM10,NO,NO2,NOx,NH3,CO,SO2,...,AQI,AQI_Bucket,Temperature,Humidity,WindSpeed,WindDirection,Rain,month,day_of_week,day_of_year
0,Delhi,2015-01-01,153.3,241.7,182.9,33.0,81.3,38.5,1.87,64.5,...,204.5,Severe,16.145833,68.083333,1.660000,95.708333,0.0,1,3,1
1,Delhi,2015-01-02,344.2,173.2,179.8,128.4,156.1,15.6,6.28,7.5,...,238.5,Satisfactory,15.037500,84.166667,1.600417,88.916667,3.4,1,4,2
2,Delhi,2015-01-03,473.9,20.1,12.7,102.7,244.7,42.5,0.04,29.8,...,77.6,Satisfactory,15.441667,84.000000,1.421667,276.791667,0.5,1,5,3
3,Delhi,2015-01-04,32.4,414.8,198.1,25.6,218.2,13.2,2.47,50.4,...,85.4,Satisfactory,14.162500,79.250000,2.807500,313.291667,0.0,1,6,4
4,Delhi,2015-01-05,312.8,155.8,143.1,106.8,6.1,4.9,4.04,2.0,...,396.8,Poor,13.995833,74.208333,5.365417,299.041667,0.0,1,0,5

In [47]:
merged.to_csv("delhi_aqi_weather_daily.csv", index=False)